# Model arguments
model_name_or_path: open-r1/Qwen2.5-Coder-7B-Instruct-SFT
model_revision: v06.11-step-000004005
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/verifiable-coding-problems-python_decontaminated

# GRPO trainer config
callbacks:
- push_to_hub_revision
benchmarks:
- lcb
beta: 0.001
bf16: true
do_eval: false
eval_strategy: "no"
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.9
do_eval: false
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: open-r1/Qwen2.5-Coder-7B-Instruct-SFT-GRPO
hub_model_revision: v00.00
hub_strategy: every_save
learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
max_grad_norm: 0.2
max_prompt_length: 1024
max_completion_length: 8192
max_steps: 1000
num_generations: 16
num_train_epochs: 1
output_dir: data/Qwen2.5-Coder-7B-Instruct-SFT-GRPO
overwrite_output_dir: true
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- wandb
reward_funcs:
- code
reward_weights:
- 1.0
save_strategy: "steps"
save_steps: 0.1
save_total_limit: 1
seed: 42
temperature: 0.7
wandb_entity: huggingface 
wandb_project: open-r1
warmup_ratio: 0.1