# Processes for accelerate
num_processes: 7

# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/LIMO
dataset_configs:
- all

# GRPO trainer config
bf16: true
eval_strategy: 'no'
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: open-r1/DeepSeek-R1-Distill-Qwen-1.5B-GRPO-LIMO
hub_strategy: every_save
learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 4096
max_steps: -1
num_generations: 7
num_train_epochs: 3
output_dir: data/DeepSeek-R1-Distill-Qwen-1.5B-GRPO-LIMO
overwrite_output_dir: true 
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 20
callbacks:
- push_to_hub_revision
benchmarks:
- math_500
- aime24
- gpqa
seed: 42
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
warmup_ratio: 0.1
